name: Mi Primer Workflow

on:
  push:
    branches:
         - qa

jobs: 
   ejemplo:
      runs-on: ubuntu-latest
      env:
        PLATAFORMA: "AWS"
        REGION: "us-east-1"
      steps:
        - name: Mostrar Variables
          run: | 
           echo "Plataforma: $PLATAFORMA"
           echo: "Región: $REGION"
        
