name: Mi Primer Workflow

on:
  push:
    branches:
         - qa

jobs: 
   ejemplo:
      runs-on: ubuntu-latest
      steps:
        - name: Mostrar API Key (No se mostrará por seguridad)
          run: | 
            echo "API Key: ${{ secrets.API_KEY }}"
        
          
           
        
