name: Mi Primer Workflow

on:
  push:
    branches:
         - qa

jobs: 
   ejemplo:
      runs-on: ubuntu-latest
      steps:
        - name: Mostrar información del Evento
          run: | 
            echo "Repositorio: ${{ github.repository }}"
            echo "Actor: ${{ github.actor }}"
            echo "Evento: ${{ github.event_name }}"
        
          
           
        
